services:
    Asdoria\SyliusQuoteRequestPlugin\Shop\QuoteController:
        public: true
        arguments:
            $twig: '@twig'
            $formFactory: '@form.factory'
            $bulkAddToCartCommandFactory: '@App\Factory\BulkAddToCartCommandFactory'
            $validator: '@validator'
            $urlGenerator: '@sylius.router.checkout_state'
            $orderModifier: '@sylius.order_modifier'
            $cartManager: '@sylius.manager.order'
            $validationGroups: '%sylius.form.type.order_item.validation_groups%'
        calls:
            - [ setQuoteSessionStorage, ['@app.storage.quote_session']]
            - [ setChannelContext, ['@sylius.context.channel']]
