services:
    Asdoria\SyliusQuoteRequestPlugin\EmailManager\ContactEmailManager:
        decorates: sylius.email_manager.contact
        arguments:
            $inner: "@Asdoria\SyliusQuoteRequestPlugin\EmailManager\ContactEmailManager.inner"
        calls:
            - [ setQuoteSessionStorage, ['@app.storage.quote_session']]
