services:
    Asdoria\SyliusQuoteRequestPlugin\EventListener\QuoteRequestListener:
        arguments:
            $emailSender: "@sylius.email_sender"
            $localeContext: "@sylius.context.locale"
        calls:
            - [ setQuoteContext, ["@asdoria_quote_request.context.quote"]]
            - [ setLogger, ["@logger"]]
        tags:
            - { name: kernel.event_listener, event: 'asdoria_quote_request.contact_email_manager.pre_send' , method: processQuoteRequest }
