services:
    Asdoria\SyliusQuoteRequestPlugin\Factory\BulkAddToCartCommandFactory:
        arguments:
          $bulkAddToCartCommandFactory: '@Asdoria\SyliusQuickShoppingPlugin\Factory\BulkAddToCartCommandFactory'
          $requestStack: '@request_stack'
          $productRepository: '@sylius.repository.product'
          $orderRepository: '@sylius.repository.order'
          $orderItemQuantityModifier: '@sylius.order_item_quantity_modifier'
          $addToCartCommandFactory: '@Asdoria\SyliusQuickShoppingPlugin\Factory\AddToCartCommandFactory'
        calls:
          - [ setQuoteSessionStorage, ['@app.storage.quote_session']]
          - [ setChannelContext, ['@sylius.context.channel']]
          - [ setEntityManager, ['@doctrine.orm.default_entity_manager']]
