services:
    asdoria_quote_request.email_manager.contact:
        class: Asdoria\SyliusQuoteRequestPlugin\EmailManager\ContactEmailManager
        decorates: sylius.email_manager.contact
        arguments:
            $inner: "@asdoria_quote_request.email_manager.contact.inner"
            $eventDispatcher: "@event_dispatcher"
