services:
    Asdoria\SyliusQuoteRequestPlugin\Factory\AddToQuoteCommandFactory:

    asdoria_quote_request.factory.quote_item:
        parent: sylius.factory.cart_item
    
    Asdoria\SyliusQuoteRequestPlugin\Factory\BulkAddToQuoteCommandFactory:
        arguments:
            $inner: '@Asdoria\SyliusQuickShoppingPlugin\Factory\BulkAddToCartCommandFactory'
            $addToCartCommandFactory: '@Asdoria\SyliusQuoteRequestPlugin\Factory\AddToQuoteCommandFactory'

    Asdoria\SyliusQuoteRequestPlugin\Factory\CustomerAfterQuoteRequestFactory:
        arguments:
            $customerRepository: '@sylius.repository.customer'
            $canonicalizer: '@sylius.canonicalizer'
            $customerFactory: '@sylius.factory.customer'
