asdoria_quote_request_shop:
    resource: "routes/shop.yaml"
    prefix: /{_locale}/quote-request
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
