framework:
    assets:
        packages:
            asdoria_sylius_quote_request_plugin:
                base_path: '/bundles/asdoriasyliusquoterequestplugin'

sylius_ui:
    events:
        asdoria.shop.index_quote_request.javascripts:
            blocks:
                comparator:
                    template: "@AsdoriaSyliusQuoteRequestPlugin/Shop/_javascripts.html.twig"
                    priority: 5


twig:
    globals:
        quote_storage: '@asdoria_quote_request.storage.quote_session'
